- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Stop and remove previous container (if exists)
    command: docker stop mywebapp && docker rm mywebapp
    ignore_errors: yes  # Ignore errors if the container doesn't exist
  - name: Remove previous image (if exists)
    command: docker rmi myapp:0.01.test1 tomcat:9.0 maven:3.6.3-jdk-8-slim
    ignore_errors: yes  # Ignore errors if the image doesn't exist
  - name: clone a repo
    git: repo=https://github.com/Pranayinfo/DevOpsClassCodes2.git dest=/tmp/jenkinsdir
  - name: build docker file
    command: chdir=/tmp/jenkinsdir docker build -t myapp:0.01.test1 .
  - name: create container
    command: docker run -dt --name mywebapp -P myapp:0.01.test1
  
